### ISSUE TITLE
My fortnite cat flip me of!11!!!1!!

### ISSUE THREAD

**Issue by Noffie1** [shalzuth/UnrealSharp#10]
![image](https://user-images.githubusercontent.com/95167583/146685794-480c8d8d-8d5b-4ed1-81be-0c2cd635b95c.png)
![image](https://user-images.githubusercontent.com/95167583/146685795-30e64b94-ac35-434f-91f0-a02bfd7bb2bc.png)
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by Kyiro** [comment]
Why?
