### ISSUE TITLE
Error when calling functions 

### ISSUE THREAD

**Issue by Ender-0001** [shalzuth/UnrealSharp#2]
When i call functions with params like (switchlevel) i get this error "'UnrealSharp.UEObject' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed."

**Comment by io-dine** [comment]
skill issue

**Comment by shalzuth** [comment]
partially fixed with https://github.com/shalzuth/UnrealSharp/commit/cac0bdbc791f79f632bafe8c7a2076aa13f089b0 for enums, still need to fix objects/structs though

**Comment by Ender-0001** [comment]
thanks
