### ISSUE TITLE
CS0246: The type or namespace name 'DeveloperSettings' could not be found

### ISSUE THREAD

**Issue by Y-A-K-E** [shalzuth/UnrealSharp#3]
games :
Torchlight III 
ENDER LILIES
Killsquad
----
I need to manually delete all "DeveloperSettings" code.

**Comment by shalzuth** [comment]
Not sure why - feel free to make a PR :)

**Comment by Y-A-K-E** [comment]
thanks, 
pull #4 is fix it.
