### ISSUE TITLE
is there a way too hook into processevent?

### ISSUE THREAD

**Issue by Ender-0001** [shalzuth/UnrealSharp#5]
can you hook into process event?

**Comment by shalzuth** [comment]
It’s possible but not currently in this. Why?

**Comment by Ender-0001** [comment]
so you can tell when certain functions are called.

**Comment by Noffie1** [comment]
![image](https://user-images.githubusercontent.com/95167583/146685773-09eb1527-cecc-479c-91e1-bc023911e118.png)
