### ISSUE TITLE
How to call a function?

### ISSUE THREAD

**Issue by Y-A-K-E** [shalzuth/UnrealSharp#6]
https://github.com/shalzuth/DeepRockGahactic/blob/main/SDK/SDK/FSD.cs

line 8562

```
    public class FSDSteamUtils : BlueprintFunctionLibrary
    {
        
        public Object GetPlayerSteamName() { return Invoke<Object>(nameof(GetPlayerSteamName)); }
        
    }
```

I want to call `GetPlayerSteamName()`.and print.

```
                var sb = new StringBuilder();
                sb.AppendLine("Shalzuth's Helper Tool");
                sb.AppendLine("FPS : " + esp.MeasuredFps.ToString("0.00"));
                sb.AppendLine("Steam Name: " + Sname);  // <--print 
```

I need an example. Thank you.

**Comment by shalzuth** [comment]
Need to either:
1. Find a reference to FSDSteamUtils somewhere else
2. Create an instance of it.

**Comment by Y-A-K-E** [comment]
"FSDSteamUtils" is not reference anywhere.

![Screenshot 2021-08-09 121956](https://user-images.githubusercontent.com/6988291/128660088-9200800e-09be-4e23-86e2-86e6f0ddd6b0.jpg)

Can't I call this function?
