### ISSUE TITLE
Extra returns?

### ISSUE THREAD

**Issue by laconicdesigns** [shalzuth/UnrealSharp#7]
https://github.com/shalzuth/UnrealSharp/blob/54db8d4457d31142a4667a71c3c9d602eb64f876/UnrealSharp/Engine/Hotkeys.cs#L36

It's not going to touch those 4 other returns at the end, so why is this written this way?

**Comment by Noffie1** [comment]
![image](https://user-images.githubusercontent.com/95167583/146685761-1657db6e-f2bf-42ac-9aa1-ccf154bd63a6.png)

**Comment by shalzuth** [comment]
It is leftover debug code. I could delete it / comment it out, but I think I left it there to remind me of what doesn't work. The c# compiler should ignore it completely.
